language: node_js
node_js: '8.9'
script:
  - npm run build
  - travis_retry npm run travis
sudo: false
dist: trusty
cache:
  directories:
    - node_modules
addons:
  sauce_connect:
    username: "quill"
    # There is no way to securely allow community PRs to be built and tested
    # by Travis and SauceLabs. Please do not abuse.
    access_key: "ced60aed-80ad-436b-9ba8-690ed1205180"
env:
  matrix:
    - BROWSER=mac-chrome-latest
    - BROWSER=mac-firefox-latest
    - BROWSER=mac-safari-latest
    - BROWSER=windows-chrome-latest
    - BROWSER=windows-firefox-latest
    - BROWSER=windows-edge-latest
    - BROWSER=ios-latest
    - BROWSER=android-latest
